back/src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_product;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description_product;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $reduction_product;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity_product;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category_product;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_product;

    // /**
    //  * @ORM\ManyToOne(targetEntity=Orders::class, inversedBy="id_article")
    //  * @ORM\JoinColumn(nullable=true)
    //  */
    // private $orders;
    
    /**
     * @ORM\OneToMany(targetEntity=Orders::class, mappedBy="product")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=Opinion::class, mappedBy="product")
     */
    private $opinions;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price_10ml;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price_30ml;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price_50ml;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price_100ml;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price_200ml;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->prices = new ArrayCollection();
        $this->opinions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameProduct(): ?string
    {
        return $this->name_product;
    }

    public function setNameProduct(string $name_product): self
    {
        $this->name_product = $name_product;

        return $this;
    }

    public function getDescriptionProduct(): ?string
    {
        return $this->description_product;
    }

    public function setDescriptionProduct(?string $description_product): self
    {
        $this->description_product = $description_product;

        return $this;
    }

    public function getReductionProduct(): ?int
    {
        return $this->reduction_product;
    }

    public function setReductionProduct(int $reduction_product): self
    {
        $this->reduction_product = $reduction_product;

        return $this;
    }

    public function getQuantityProduct(): ?int
    {
        return $this->quantity_product;
    }

    public function setQuantityProduct(int $quantity_product): self
    {
        $this->quantity_product = $quantity_product;

        return $this;
    }

    public function getCategoryProduct(): ?string
    {
        return $this->category_product;
    }

    public function setCategoryProduct(string $category_product): self
    {
        $this->category_product = $category_product;

        return $this;
    }

    public function getImageProduct(): ?string
    {
        return $this->image_product;
    }

    public function setImageProduct(?string $image_product): self
    {
        $this->image_product = $image_product;

        return $this;
    }


    /**
     * @return Collection|Orders[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Orders $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setProduct($this);
        }

        return $this;
    }

    public function removeOrder(Orders $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getProduct() === $this) {
                $order->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Opinion[]
     */
    public function getOpinions(): Collection
    {
        return $this->opinions;
    }

    public function addOpinion(Opinion $opinion): self
    {
        if (!$this->opinions->contains($opinion)) {
            $this->opinions[] = $opinion;
            $opinion->setProduct($this);
        }

        return $this;
    }

    public function removeOpinion(Opinion $opinion): self
    {
        if ($this->opinions->removeElement($opinion)) {
            // set the owning side to null (unless already changed)
            if ($opinion->getProduct() === $this) {
                $opinion->setProduct(null);
            }
        }

        return $this;
    }

    public function getPrice10ml(): ?float
    {
        return $this->price_10ml;
    }

    public function setPrice10ml(?float $price_10ml): self
    {
        $this->price_10ml = $price_10ml;

        return $this;
    }

    public function getPrice30ml(): ?float
    {
        return $this->price_30ml;
    }

    public function setPrice30ml(?float $price_30ml): self
    {
        $this->price_30ml = $price_30ml;

        return $this;
    }

    public function getPrice50ml(): ?float
    {
        return $this->price_50ml;
    }

    public function setPrice50ml(?float $price_50ml): self
    {
        $this->price_50ml = $price_50ml;

        return $this;
    }

    public function getPrice100ml(): ?float
    {
        return $this->price_100ml;
    }

    public function setPrice100ml(?float $price_100ml): self
    {
        $this->price_100ml = $price_100ml;

        return $this;
    }

    public function getPrice200ml(): ?float
    {
        return $this->price_200ml;
    }

    public function setPrice200ml(?float $price_200ml): self
    {
        $this->price_200ml = $price_200ml;

        return $this;
    }

}

back/src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_product')
            ->add('description_product')
            ->add('reduction_product')
            ->add('quantity_product')
            ->add('category_product')
            ->add('image_product')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

back/src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Entity\Opinion;
// use App\Form\ProductType;
// use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/product")
 */
class ProductController extends AbstractController
{
    // /**
    //  * @Route("/", name="product_index", methods={"GET"})
    //  */
    // public function index(ProductRepository $productRepository): Response
    // {
    //     dd($productRepository);
    //     return $this->render('product/index.html.twig', [
    //         'products' => $productRepository->findAll(),
    //     ]);
    // }

    /**
     * @Route("/create", name="product_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, ManagerRegistry $doctrine): Response
    {
        $newProduct = $request->request;
        $verifyProduct = $doctrine->getRepository(Product::class)->findBy([
            'name_product' => $newProduct->get('name_product'),
        ]);

        if (!$verifyProduct) {
            $product = new Product();
            $product->setNameProduct($newProduct->get('name_product'));
            $product->setCategoryProduct($newProduct->get('category_product'));
            $product->setQuantityProduct($newProduct->get('quantity_product'));
            $product->setPrice10ml(0);
            $product->setPrice30ml(0);
            $product->setPrice50ml(0);
            $product->setPrice100ml(0);
            $product->setPrice200ml(0);

            $entityManager->persist($product);
            $entityManager->flush();
            return $this->json([
                "success" => 200
            ]);
        } else {
            return $this->json([
                "error" => "this product already exist"
            ]);
        }
    }

    /**
     * @Route("/read/id", name="product_show_ID", methods={"POST"})
     */
    public function showId(Request $request, ManagerRegistry $doctrine): Response
    {
        $requete = $request->request;

        $product = $doctrine
            ->getRepository(Product::class)
            ->findOneBy([
                "id" => $requete->get("id")
            ]);

        if (!empty($product)) {
            return $this->json([
                "product" =>  $product
            ]);
        } else {
            return $this->json([
                "error" =>  "product not found"
            ]);
        }
    }

    /**
     * @Route("/read/all", name="product_show_all", methods={"POST"})
     */
    public function showAll(Request $request, ManagerRegistry $doctrine): Response
    {
        $requete = $request->request;

        $product = $doctrine
            ->getRepository(Product::class)
            ->findAll();

        if (!empty($product)) {
            return $this->json([
                "product" =>  $product
            ]);
        } else {
            return $this->json([
                "error" =>  "can't find any product"
            ]);
        }
    }

    /**
     * @Route("/update", name="product_edit", methods={"POST"})
     */
    public function edit(ManagerRegistry $doctrine, Request $request): Response
    {
        $entityManager = $doctrine->getManager();

        $newProduct = $request->request;

        $productProfile = $doctrine
            ->getRepository(Product::class)
            ->findOneBy([
                "id" => $newProduct->get("id")
            ]);

        foreach ($newProduct as $key => $value) {
            switch ($key) {
                case 'name_product':
                    $productProfile->setNameProduct($value);
                    break;
                case 'description_product':
                    $productProfile->setDescriptionProduct($value);
                    break;
                case 'category_product':
                    $productProfile->setCategoryProduct($value);
                    break;
                case 'image_product':
                    $productProfile->setImageProduct($value);
                    break;
                case 'quantity_product':
                    $productProfile->setQuantityProduct($value);
                    break;
                case 'price_product':
                    $productProfile->setPriceProduct($value);
                    break;
                case 'price_10ml':
                    $productProfile->setPrice10ml($value);
                    break;
                case 'price_30ml':
                    $productProfile->setPrice30ml($value);
                    break;
                case 'price_50ml':
                    $productProfile->setPrice50ml($value);
                    break;
                case 'price_10ml':
                    $productProfile->setPrice100ml($value);
                    break;
                case 'price_10ml':
                    $productProfile->setPrice200ml($value);
                    break;
            }
        }

        $entityManager->flush();

        return $this->json([
            "success" => "your products has been updated"
        ]);
    }

    /**
     * @Route("/delete", name="product_delete", methods={"POST"})
     */
    public function delete(Request $request, ManagerRegistry $doctrine): Response
    {

        $newProduct = $request->request;
        $entityManager = $doctrine->getManager();

        $verifyProduct = $doctrine
            ->getRepository(Product::class)
            ->findOneBy([
                'id' => $newProduct->get('id'),
            ]);
        $entityManager->remove($verifyProduct);
        $entityManager->flush();
        return $this->json([
            "success" => 200
        ]);
    }
}

back/templates/product/_delete_form.html.twig
<form method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
    <button class="btn">Delete</button>
</form>

back/templates/product/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

back/templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Product{% endblock %}

{% block body %}
    <h1>Edit Product</h1>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('product_index') }}">back to list</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}

back/templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product index{% endblock %}

{% block body %}
    <h1>Product index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_product</th>
                <th>Description_product</th>
                <th>Reduction_product</th>
                <th>Quantity_product</th>
                <th>Category_product</th>
                <th>Image_product</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>
                <td>{{ product.nameProduct }}</td>
                <td>{{ product.descriptionProduct }}</td>
                <td>{{ product.reductionProduct }}</td>
                <td>{{ product.quantityProduct }}</td>
                <td>{{ product.categoryProduct }}</td>
                <td>{{ product.imageProduct }}</td>
                <td>
                    <a href="{{ path('product_show', {'id': product.id}) }}">show</a>
                    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('product_new') }}">Create new</a>
{% endblock %}

back/templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Product{% endblock %}

{% block body %}
    <h1>Create new Product</h1>

    {{ include('product/_form.html.twig') }}

    <a href="{{ path('product_index') }}">back to list</a>
{% endblock %}

back/templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Product{% endblock %}

{% block body %}
    <h1>Product</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ product.id }}</td>
            </tr>
            <tr>
                <th>Name_product</th>
                <td>{{ product.nameProduct }}</td>
            </tr>
            <tr>
                <th>Description_product</th>
                <td>{{ product.descriptionProduct }}</td>
            </tr>
            <tr>
                <th>Reduction_product</th>
                <td>{{ product.reductionProduct }}</td>
            </tr>
            <tr>
                <th>Quantity_product</th>
                <td>{{ product.quantityProduct }}</td>
            </tr>
            <tr>
                <th>Category_product</th>
                <td>{{ product.categoryProduct }}</td>
            </tr>
            <tr>
                <th>Image_product</th>
                <td>{{ product.imageProduct }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('product_index') }}">back to list</a>

    <a href="{{ path('product_edit', {'id': product.id}) }}">edit</a>

    {{ include('product/_delete_form.html.twig') }}
{% endblock %}